name: Générer les APKs Android (User & Driver)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
      - '.github/workflows/**'

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [user-app, driver-app]
    name: Build ${{ matrix.app }}
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Installation des dépendances
        working-directory: ./mobile/${{ matrix.app }}
        run: npm install --legacy-peer-deps

      - name: Génération des fichiers natifs Android (Prebuild)
        working-directory: ./mobile/${{ matrix.app }}
        run: npx expo prebuild --platform android --clean
        env:
          EXPO_PUBLIC_API_URL: "https://papeterie.vercel.app/api"
          CI: 1

      - name: Compilation de l'APK (Gradle)
        working-directory: ./mobile/${{ matrix.app }}/android
        run: ./gradlew assembleRelease

      - name: Upload de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: papeterie-${{ matrix.app }}-apk
          path: mobile/${{ matrix.app }}/android/app/build/outputs/apk/release/app-release.apk
